feat(cardano): add support for collateral inputs
vacuumlabs/trezor-firmware pull request #70
Opened 2021-09-02 10:54 UTC by davidmisiak

2021-09-04 19:02 UTC, gabrielKerekes requested changes
This looks pretty good for now. At the moment I am not sure if it won't be needed/better to have a separate protobuf type for the collateral inputs as they might include different fields in the future. For now, let's add it as a todo item to the PRs description to "make sure we don't need a separate `CollateralInput` protobuf message".

Also let's also add todo entries for "re-consider the `confirm_collateral_input` wording" and "show `collateral_input.prev_hash` as bech32?", "use proper signing mode" and "how will collateral inputs be witnessed - determined by client or passed in via additional witnesses?". Those are the things which are yet unclear to us I think and we should not forget to resolve them later.

2021-09-06 10:00 UTC, davidmisiak commented on common/protob/messages-cardano.proto
> +    required uint32 collateral_count = 14;
This was exactly my dilemma when I was writing the code. Originally, I named it `collateral_inputs` everywhere, but then I came across [this paragraph](https://hydra.iohk.io/build/7172824/download/1/alonzo-changes.pdf#subsection.3.2) about the new transaction structure, where they call it `collateral`, so I stripped the `_inputs`. But I don't insist on this at all, so I'm going to change it back if you think it's better.

2021-09-06 10:39 UTC, davidmisiak commented on common/protob/messages-cardano.proto
> +    required uint32 collateral_count = 14;
Done

2021-09-07 10:29 UTC, gabrielKerekes approved these changes

2021-10-21 18:03 UTC, closed without merging